//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceAlmacen
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/WS_ALMACEN")]
    public partial class Producto : object
    {
        
        private string NombreProductoField;
        
        private string NumeroProductoField;
        
        private decimal PrecioField;
        
        private string TipoTransaccionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProducto
        {
            get
            {
                return this.NombreProductoField;
            }
            set
            {
                this.NombreProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroProducto
        {
            get
            {
                return this.NumeroProductoField;
            }
            set
            {
                this.NumeroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio
        {
            get
            {
                return this.PrecioField;
            }
            set
            {
                this.PrecioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTransaccion
        {
            get
            {
                return this.TipoTransaccionField;
            }
            set
            {
                this.TipoTransaccionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="http://schemas.datacontract.org/2004/07/WS_ALMACEN")]
    public partial class Resultado : object
    {
        
        private string MensajeField;
        
        private bool ResultadoOperacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ResultadoOperacion
        {
            get
            {
                return this.ResultadoOperacionField;
            }
            set
            {
                this.ResultadoOperacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/WS_ALMACEN")]
    public partial class Proveedor : object
    {
        
        private string CedulaJuridicaField;
        
        private string CorreoField;
        
        private string EstadoField;
        
        private string NombreContactoField;
        
        private string NombreEmpresaField;
        
        private string TelefonoField;
        
        private string TipoTransaccionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CedulaJuridica
        {
            get
            {
                return this.CedulaJuridicaField;
            }
            set
            {
                this.CedulaJuridicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreContacto
        {
            get
            {
                return this.NombreContactoField;
            }
            set
            {
                this.NombreContactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpresa
        {
            get
            {
                return this.NombreEmpresaField;
            }
            set
            {
                this.NombreEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTransaccion
        {
            get
            {
                return this.TipoTransaccionField;
            }
            set
            {
                this.TipoTransaccionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compra", Namespace="http://schemas.datacontract.org/2004/07/WS_ALMACEN")]
    public partial class Compra : object
    {
        
        private string CedulaJuridicaField;
        
        private System.DateTime FechaCompraField;
        
        private string NumeroIngresoField;
        
        private ServiceReferenceAlmacen.DetalleProducto[] ProductosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CedulaJuridica
        {
            get
            {
                return this.CedulaJuridicaField;
            }
            set
            {
                this.CedulaJuridicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCompra
        {
            get
            {
                return this.FechaCompraField;
            }
            set
            {
                this.FechaCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroIngreso
        {
            get
            {
                return this.NumeroIngresoField;
            }
            set
            {
                this.NumeroIngresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceAlmacen.DetalleProducto[] Productos
        {
            get
            {
                return this.ProductosField;
            }
            set
            {
                this.ProductosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleProducto", Namespace="http://schemas.datacontract.org/2004/07/WS_ALMACEN")]
    public partial class DetalleProducto : object
    {
        
        private int CantidadField;
        
        private string NumeroProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroProducto
        {
            get
            {
                return this.NumeroProductoField;
            }
            set
            {
                this.NumeroProductoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAlmacen.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProcesarProducto", ReplyAction="http://tempuri.org/IService/ProcesarProductoResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAlmacen.Resultado> ProcesarProductoAsync(ServiceReferenceAlmacen.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProcesarProveedor", ReplyAction="http://tempuri.org/IService/ProcesarProveedorResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAlmacen.Resultado> ProcesarProveedorAsync(ServiceReferenceAlmacen.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProcesarCompra", ReplyAction="http://tempuri.org/IService/ProcesarCompraResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAlmacen.Resultado> ProcesarCompraAsync(ServiceReferenceAlmacen.Compra compra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServiceChannel : ServiceReferenceAlmacen.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<ServiceReferenceAlmacen.IService>, ServiceReferenceAlmacen.IService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAlmacen.Resultado> ProcesarProductoAsync(ServiceReferenceAlmacen.Producto producto)
        {
            return base.Channel.ProcesarProductoAsync(producto);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAlmacen.Resultado> ProcesarProveedorAsync(ServiceReferenceAlmacen.Proveedor proveedor)
        {
            return base.Channel.ProcesarProveedorAsync(proveedor);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAlmacen.Resultado> ProcesarCompraAsync(ServiceReferenceAlmacen.Compra compra)
        {
            return base.Channel.ProcesarCompraAsync(compra);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55246/Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService,
        }
    }
}
