//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceAutenticacion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutenticacionResponse", Namespace="http://schemas.datacontract.org/2004/07/WebServiceAuten")]
    public partial class AutenticacionResponse : object
    {
        
        private bool ResultadoField;
        
        private string IdField;
        
        private string MensajeField;
        
        private string DetalleField;
        
        private ServiceReferenceAutenticacion.AutenticacionResponse.UsuarioDto UsuarioField;
        
        private ServiceReferenceAutenticacion.AutenticacionResponse.UsuarioDto[] ListaUsuariosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Detalle
        {
            get
            {
                return this.DetalleField;
            }
            set
            {
                this.DetalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public ServiceReferenceAutenticacion.AutenticacionResponse.UsuarioDto Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public ServiceReferenceAutenticacion.AutenticacionResponse.UsuarioDto[] ListaUsuarios
        {
            get
            {
                return this.ListaUsuariosField;
            }
            set
            {
                this.ListaUsuariosField = value;
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="AutenticacionResponse.UsuarioDto", Namespace="http://schemas.datacontract.org/2004/07/WebServiceAuten")]
        public partial class UsuarioDto : object
        {
            
            private string CorreoField;
            
            private string EstadoField;
            
            private string IdentificacionField;
            
            private string NombreField;
            
            private string PrimerApellidoField;
            
            private string SegundoApellidoField;
            
            private int TipoField;
            
            private string UsuarioField;
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Correo
            {
                get
                {
                    return this.CorreoField;
                }
                set
                {
                    this.CorreoField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Estado
            {
                get
                {
                    return this.EstadoField;
                }
                set
                {
                    this.EstadoField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Identificacion
            {
                get
                {
                    return this.IdentificacionField;
                }
                set
                {
                    this.IdentificacionField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Nombre
            {
                get
                {
                    return this.NombreField;
                }
                set
                {
                    this.NombreField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string PrimerApellido
            {
                get
                {
                    return this.PrimerApellidoField;
                }
                set
                {
                    this.PrimerApellidoField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string SegundoApellido
            {
                get
                {
                    return this.SegundoApellidoField;
                }
                set
                {
                    this.SegundoApellidoField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public int Tipo
            {
                get
                {
                    return this.TipoField;
                }
                set
                {
                    this.TipoField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Usuario
            {
                get
                {
                    return this.UsuarioField;
                }
                set
                {
                    this.UsuarioField = value;
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAutenticacion.IAutenticacion")]
    public interface IAutenticacion
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/AutenticarUsuario", ReplyAction="http://tempuri.org/IAutenticacion/AutenticarUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAutenticacion.AutenticacionResponse> AutenticarUsuarioAsync(string usuario, string contrasenia, int tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/CrearUsuario", ReplyAction="http://tempuri.org/IAutenticacion/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAutenticacion.AutenticacionResponse> CrearUsuarioAsync(string identificacion, string nombre, string primerApellido, string segundoApellido, string correo, string usuario, string contrasenia, string estado, int tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/ModificarUsuario", ReplyAction="http://tempuri.org/IAutenticacion/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAutenticacion.AutenticacionResponse> ModificarUsuarioAsync(string usuario, string nombre, string primerApellido, string segundoApellido, string correo, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/CambiarEstadoUsuario", ReplyAction="http://tempuri.org/IAutenticacion/CambiarEstadoUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAutenticacion.AutenticacionResponse> CambiarEstadoUsuarioAsync(string identificacion, string nuevoEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/EliminarUsuario", ReplyAction="http://tempuri.org/IAutenticacion/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAutenticacion.AutenticacionResponse> EliminarUsuarioAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacion/ObtenerUsuarios", ReplyAction="http://tempuri.org/IAutenticacion/ObtenerUsuariosResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAutenticacion.AutenticacionResponse> ObtenerUsuariosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IAutenticacionChannel : ServiceReferenceAutenticacion.IAutenticacion, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AutenticacionClient : System.ServiceModel.ClientBase<ServiceReferenceAutenticacion.IAutenticacion>, ServiceReferenceAutenticacion.IAutenticacion
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AutenticacionClient() : 
                base(AutenticacionClient.GetDefaultBinding(), AutenticacionClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAutenticacion.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutenticacionClient(EndpointConfiguration endpointConfiguration) : 
                base(AutenticacionClient.GetBindingForEndpoint(endpointConfiguration), AutenticacionClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutenticacionClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AutenticacionClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutenticacionClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AutenticacionClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutenticacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAutenticacion.AutenticacionResponse> AutenticarUsuarioAsync(string usuario, string contrasenia, int tipo)
        {
            return base.Channel.AutenticarUsuarioAsync(usuario, contrasenia, tipo);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAutenticacion.AutenticacionResponse> CrearUsuarioAsync(string identificacion, string nombre, string primerApellido, string segundoApellido, string correo, string usuario, string contrasenia, string estado, int tipo)
        {
            return base.Channel.CrearUsuarioAsync(identificacion, nombre, primerApellido, segundoApellido, correo, usuario, contrasenia, estado, tipo);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAutenticacion.AutenticacionResponse> ModificarUsuarioAsync(string usuario, string nombre, string primerApellido, string segundoApellido, string correo, string contrasenia)
        {
            return base.Channel.ModificarUsuarioAsync(usuario, nombre, primerApellido, segundoApellido, correo, contrasenia);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAutenticacion.AutenticacionResponse> CambiarEstadoUsuarioAsync(string identificacion, string nuevoEstado)
        {
            return base.Channel.CambiarEstadoUsuarioAsync(identificacion, nuevoEstado);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAutenticacion.AutenticacionResponse> EliminarUsuarioAsync(string usuario)
        {
            return base.Channel.EliminarUsuarioAsync(usuario);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAutenticacion.AutenticacionResponse> ObtenerUsuariosAsync()
        {
            return base.Channel.ObtenerUsuariosAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAutenticacion))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAutenticacion))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:53328/Autenticacion.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AutenticacionClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAutenticacion);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AutenticacionClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAutenticacion);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAutenticacion,
        }
    }
}
